version: '3.4'
services:
    php56:
        build: ./php/php56/
        ports:
            - "9001:9000"
        privileged: true
        volumes:
            - /var/www:/var/www:rw
            - ./logs/php56:/var/log/php-fpm:rw
            - ./php/php56/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./php/php56/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        restart: always
        command: php-fpm
        networks:
            - php_net
#        container_name: "compose_php_php56"
    php71:
        build: ./php/php71/
        ports:
            - "9002:9000"
        privileged: true
        volumes:
            - /var/www:/var/www:rw
            - ./logs/php71:/var/log/php-fpm:rw
            - ./php/php71/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./php/php71/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        restart: always
        command: php-fpm
        networks:
            - php_net
#        container_name: "compose_php_php71"
    php73:
        build: ./php/php73/
        ports:
            - "9003:9000"
        privileged: true
        volumes:
            - /var/www:/var/www:rw
            - ./logs/php73:/var/log/php-fpm:rw
            - ./php/php73/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./php/php73/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        restart: always
        command: php-fpm
        networks:
            - php_net
#        container_name: "compose_php_php73"
    nginx:
        build: ./nginx
        depends_on:
            - php56
            - php71
            - php73
        volumes:
            - /var/www:/var/www:rw
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./logs/nginx:/var/log/nginx:rw
        ports:
            - "80:80"
            - "8081:8080"
            - "444:443"
        privileged: true
        restart: always
        command: nginx -g 'daemon off;'
        networks:
            - php_net
        # 容器名称
        #container_name: "compose-nginx"
    mysql-db:
        build: ./mysql
        ports:
            - "3307:3306"
        privileged: true
        volumes:
            - ./data/mysql:/var/lib/mysql:rw
            - ./logs/mysql:/var/lib/mysql-logs:rw
            - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: testdb
            MYSQL_USER: test
            MYSQL_PASSWORD: 123456
        restart: always
#        command: "--character-set-server=utf8"
        networks:
            - php_net
                # 固定子网ip，网段必须在子网络10.10.*.*
                #ipv4_address: 127.20.0.1
        #container_name: "compose-mysql"
    redis-db:
          build: ./redis
          ports:
            - "6380:6379"
          volumes:
            - ./data/redis:/data
          restart: always
          networks:
            - php_net
networks:
# 配置docker network
    php_net:
        driver: bridge
        #ipam:
         #   config:
                # 子网络
          #      - subnet: 127.20.0.0/16

