version: '2'
services:
    php56:
        build: ./build/php/php56/
        ports:
            - "9011:9000"
        privileged: true
        volumes:
            - /var/www:/var/www:rw
            - ./logs/php56:/var/log/php-fpm:rw
            - ./conf/php56/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./conf/php56/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        restart: always
        command: php-fpm
        networks:
            - default
#        container_name: "compose_php_php56"
    php71:
        build: ./build/php/php71/
        ports:
            - "9012:9000"
        privileged: true
        volumes:
            - /var/www:/var/www:rw
            - ./logs/php71:/var/log/php-fpm:rw
            - ./conf/php71/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./conf/php71/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        restart: always
        command: php-fpm
        networks:
            - default
#        container_name: "compose_php_php71"
    php73:
        build: ./build/php/php73/
        ports:
            - "9013:9000"
        privileged: true
        volumes:
            - /var/www:/var/www:rw
            - ./logs/php73:/var/log/php-fpm:rw
            - ./conf/php73/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./conf/php73/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        restart: always
        command: php-fpm
        networks:
            - default
#        container_name: "compose_php_php73"
    nginx:
        build: ./build/nginx
        depends_on:
            - php56
            - php71
            - php73
        volumes:
            - /var/www:/var/www:rw
            - ./conf/nginx/conf.d:/etc/nginx/conf.d:rw
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./logs/nginx:/var/log/nginx:rw
        ports:
            - "90:80"
            - "8091:8080"
            - "454:443"
        privileged: true
        restart: always
        command: nginx -g 'daemon off;'
        networks:
            - default
        # 容器名称
        #container_name: "compose-nginx"
    mysql:
        build: ./build/mysql
        ports:
            - "3317:3306"
        privileged: true
        volumes:
            - ./data/mysql:/var/lib/mysql:rw
            - ./logs/mysql:/var/lib/mysql-logs:rw
            - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: testdb
            MYSQL_USER: test
            MYSQL_PASSWORD: 123456
        restart: always
#        command: "--character-set-server=utf8"
        networks:
            - default
                # 固定子网ip，网段必须在子网络10.10.*.*
                #ipv4_address: 127.20.0.1
        #container_name: "compose-mysql"
    redis:
          build: ./build/redis
          ports:
            - "6390:6379"
          privileged: true
          volumes:
            - ./data/redis:/data
            - ./conf/redis/redis.conf:/etc/redis.conf:ro
          restart: always
          networks:
            - default
    mongodb:
      build: ./build/mongodb
      environment:
          MONGO_INITDB_ROOT_USERNAME: "root"
          MONGO_INITDB_ROOT_PASSWORD: "123456"
      volumes:
        - ./data/mongodb:/data/db:rw
        - ./data/mongodb/mongo_key:/mongo:rw
      ports:
         - "27028:27017"
      privileged: true
      networks:
         - default
      command:
         --auth
networks:
# 配置docker network
    default:
        driver: bridge
        #ipam:
         #   config:
                # 子网络
          #      - subnet: 127.20.0.0/16

